session:
    timeout: 60
    config : localhost
    
redis: 
    host: localhost
    port: 6379
    timeout: 5

mongodb:
    host: localhost
    port: 27017

folder:
    image: E:\\doan\\image\\
    file: E:\\doan\\file\\
        
